[package]
name = "shared"
version = "0.1.0"
authors = ["Jordi Paris Ferrer <jparisferrer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pb-jelly = "0.0.4"
